[package]
name = "deepspeech-sys"
description = "Bindgen output for the DeepSpeech C++ API"
license = "MPL-2.0"
documentation = "https://docs.rs/deepspeech"
repository = "https://github.com/RustAudio/deepspeech-rs"
version = "0.5.0"
authors = ["est31 <MTest31@outlook.com>"]

include = ["deepspeech/native_client/deepspeech.h", "/src/**",
	"/build.rs", "/LICENSE", "Cargo.toml"]

[dependencies]

[build-dependencies]
bindgen = { version = "0.52", default-features = false, features = ["runtime"] }
proc-macro2 = { version = "1.0", default-features = false }
