[package]
name = "deepspeech-sys"
description = "Bindgen output for the DeepSpeech C++ API"
license = "MPL-2.0"
repository = "https://github.com/RustAudio/deepspeech-rs"
version = "0.0.1"
authors = ["est31 <MTest31@outlook.com>"]

include = ["deepspeech/native_client/**/*.h", "/src/**",
	"/build.rs", "/LICENSE"]

[dependencies]

[build-dependencies]
bindgen = "0.31"
