name: deepspeech

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Run cargo build
        run: cargo build --verbose
      - name: Run cargo doc
        run: cargo doc --verbose
      - name: run ci.sh
        run: ./ci.sh
